from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ProviderPreset:
    name: str
    description: str
    contract: str
    example: str


PRESETS = {
    "openai": ProviderPreset(
        "openai", "OpenAI or an OpenAI-compatible hosted endpoint",
        """# Generated by env-contract --init openai
OPENAI_API_KEY= # env-contract: secret required
OPENAI_BASE_URL=https://api.openai.com/v1 # env-contract: url optional
OPENAI_MODEL=gpt-4o-mini # env-contract: string optional
""",
        """# Copy to .env and fill in the secret locally.
OPENAI_API_KEY=
OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_MODEL=gpt-4o-mini
""",
    ),
    "anthropic": ProviderPreset(
        "anthropic", "Anthropic Messages API",
        """# Generated by env-contract --init anthropic
ANTHROPIC_API_KEY= # env-contract: secret required
ANTHROPIC_BASE_URL=https://api.anthropic.com # env-contract: url optional
ANTHROPIC_MODEL=claude-3-5-sonnet-latest # env-contract: string optional
""",
        """# Copy to .env and fill in the secret locally.
ANTHROPIC_API_KEY=
ANTHROPIC_BASE_URL=https://api.anthropic.com
ANTHROPIC_MODEL=claude-3-5-sonnet-latest
""",
    ),
    "gemini": ProviderPreset(
        "gemini", "Google Gemini API",
        """# Generated by env-contract --init gemini
GEMINI_API_KEY= # env-contract: secret required
GEMINI_BASE_URL=https://generativelanguage.googleapis.com/v1beta # env-contract: url optional
GEMINI_MODEL=gemini-2.0-flash # env-contract: string optional
""",
        """# Copy to .env and fill in the secret locally.
GEMINI_API_KEY=
GEMINI_BASE_URL=https://generativelanguage.googleapis.com/v1beta
GEMINI_MODEL=gemini-2.0-flash
""",
    ),
    "azure-openai": ProviderPreset(
        "azure-openai", "Azure OpenAI deployment",
        """# Generated by env-contract --init azure-openai
AZURE_OPENAI_API_KEY= # env-contract: secret required
AZURE_OPENAI_ENDPOINT= # env-contract: url required
AZURE_OPENAI_API_VERSION=2024-10-21 # env-contract: string required
AZURE_OPENAI_DEPLOYMENT= # env-contract: string required
""",
        """# Copy to .env and fill in the deployment details locally.
AZURE_OPENAI_API_KEY=
AZURE_OPENAI_ENDPOINT=
AZURE_OPENAI_API_VERSION=2024-10-21
AZURE_OPENAI_DEPLOYMENT=
""",
    ),
    "ollama": ProviderPreset(
        "ollama", "Local Ollama server",
        """# Generated by env-contract --init ollama
OLLAMA_BASE_URL=http://127.0.0.1:11434 # env-contract: url required
OLLAMA_MODEL=llama3.2 # env-contract: string required
""",
        """# Local defaults; change the model to one installed on your machine.
OLLAMA_BASE_URL=http://127.0.0.1:11434
OLLAMA_MODEL=llama3.2
""",
    ),
    "openai-compatible": ProviderPreset(
        "openai-compatible", "Any provider exposing the OpenAI-compatible API shape",
        """# Generated by env-contract --init openai-compatible
AI_API_KEY= # env-contract: secret required
AI_BASE_URL= # env-contract: url required
AI_MODEL= # env-contract: string required
""",
        """# Copy to .env and fill in the endpoint and secret locally.
AI_API_KEY=
AI_BASE_URL=
AI_MODEL=
""",
    ),
    "openrouter": ProviderPreset(
        "openrouter", "OpenRouter model gateway",
        """# Generated by env-contract --init openrouter
OPENROUTER_API_KEY= # env-contract: secret required
OPENROUTER_BASE_URL=https://openrouter.ai/api/v1 # env-contract: url optional
OPENROUTER_MODEL= # env-contract: string required
""",
        """# Copy to .env and fill in the model key locally.
OPENROUTER_API_KEY=
OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
OPENROUTER_MODEL=
""",
    ),
    "deepseek": ProviderPreset(
        "deepseek", "DeepSeek API",
        """# Generated by env-contract --init deepseek
DEEPSEEK_API_KEY= # env-contract: secret required
DEEPSEEK_BASE_URL=https://api.deepseek.com/v1 # env-contract: url optional
DEEPSEEK_MODEL=deepseek-chat # env-contract: string optional
""",
        """# Copy to .env and fill in the secret locally.
DEEPSEEK_API_KEY=
DEEPSEEK_BASE_URL=https://api.deepseek.com/v1
DEEPSEEK_MODEL=deepseek-chat
""",
    ),
    "groq": ProviderPreset(
        "groq", "Groq hosted inference API",
        """# Generated by env-contract --init groq
GROQ_API_KEY= # env-contract: secret required
GROQ_BASE_URL=https://api.groq.com/openai/v1 # env-contract: url optional
GROQ_MODEL=llama-3.3-70b-versatile # env-contract: string optional
""",
        """# Copy to .env and fill in the secret locally.
GROQ_API_KEY=
GROQ_BASE_URL=https://api.groq.com/openai/v1
GROQ_MODEL=llama-3.3-70b-versatile
""",
    ),
    "mistral": ProviderPreset(
        "mistral", "Mistral AI API",
        """# Generated by env-contract --init mistral
MISTRAL_API_KEY= # env-contract: secret required
MISTRAL_BASE_URL=https://api.mistral.ai/v1 # env-contract: url optional
MISTRAL_MODEL=mistral-small-latest # env-contract: string optional
""",
        """# Copy to .env and fill in the secret locally.
MISTRAL_API_KEY=
MISTRAL_BASE_URL=https://api.mistral.ai/v1
MISTRAL_MODEL=mistral-small-latest
""",
    ),
    "lm-studio": ProviderPreset(
        "lm-studio", "Local LM Studio OpenAI-compatible server",
        """# Generated by env-contract --init lm-studio
LM_STUDIO_BASE_URL=http://127.0.0.1:1234/v1 # env-contract: url required
LM_STUDIO_MODEL= # env-contract: string required
""",
        """# Change the model to one loaded in LM Studio.
LM_STUDIO_BASE_URL=http://127.0.0.1:1234/v1
LM_STUDIO_MODEL=
""",
    ),
}


def provider_names() -> tuple[str, ...]:
    return tuple(PRESETS)


def get_provider(name: str) -> ProviderPreset:
    try:
        return PRESETS[name]
    except KeyError as exc:
        choices = ", ".join(provider_names())
        raise ValueError(f"unknown provider '{name}' (choose from: {choices})") from exc
